version: "2"

services:
    datanode:
      image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
      container_name: het
      restart: always
      volumes:
        - hadoop_datanode:/hadoop/dfs/data
      environment:
        SERVICE_PRECONDITION: "192.168.1.29:9000"
      env_file:
        - ./hadoop.env

  
volumes:
  hadoop_datanode:

